theme = "nordic"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[editor]
line-number = "relative"
auto-pairs = false

[editor.whitespace.render]
nbsp = "all"

[editor.whitespace.characters]
nbsp = "_"

[editor.smart-tab]
enable = true

[keys.normal]
C-d = "@miwv*n"
C-y = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"

[editor.statusline]
center = ["file-type"]
